sudo: false

language: php

php:
  - 5.5

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: hhvm

before_script:
  - composer install

script: phpunit
