<?php

namespace Boots\Installer;

/**
 * This file is part of the Boots\Installer package.
 *
 * @package    Boots\Installer
 * @subpackage FrameworkInstaller
 * @author     Kamal Khan <shout@bhittani.com>
 * @version    1.x
 * @see        http://wpboots.com
 * @link       https://github.com/wpboots/installer
 * @copyright  2014-2017 Kamal Khan
 * @license    https://github.com/wpboots/installer/blob/master/LICENSE
 */

use Composer\Package\PackageInterface;
use Composer\Installer\LibraryInstaller;
use Composer\Repository\InstalledRepositoryInterface;

/**
 * @package Boots\Installer
 * @subpackage FrameworkInstaller
 */
class FrameworkInstaller extends LibraryInstaller
{
    /**
     * Extension type.
     * @var string
     */
    protected $framework = 'boots/boots';

    /**
     * Target directory (relative to project).
     * @var string
     */
    protected $targetDir = 'boots';

    /**
     * Config file (relative to package).
     * @var string
     */
    protected $configFile = 'boots.php';

    protected static function readConfig($path)
    {
        $config = ['version' => '', 'mounted' => false, 'extensions' => []];
        if (is_file($path)) {
            $config = require $path;
        }
        return $config;
    }

    protected static function writeConfig($path, array $config)
    {
        $contents = '<?php ' . PHP_EOL;
        $contents .= '// This file is automatically generated by the' . PHP_EOL;
        $contents .= '// boots framework and SHOULD NOT be modified directly.' . PHP_EOL;
        $contents .= 'return ' . var_export($config, true) . ';' . PHP_EOL;
        file_put_contents($path, $contents);
    }

    protected function getAbsolutePath(PackageInterface $package)
    {
        $baseDir = dirname($this->composer->getConfig()->getConfigSource()->getName());
        $installPath = $this->getInstallPath($package);
        return "{$baseDir}/{$installPath}";
    }

    /**
     * {@inheritDoc}
     */
    public function getInstallPath(PackageInterface $package)
    {
        if ($package->getPrettyName() !== $this->framework) {
            return parent::getInstallPath($package);
        }

        return $this->targetDir;
    }

    /**
     * {@inheritDoc}
     */
    public function supports($packageType)
    {
        return $packageType === 'framework';
    }

    /**
     * {@inheritDoc}
     */
    public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        if ($package->getPrettyName() !== $this->framework) {
            return parent::install($repo, $package);
        }

        $path = $this->getAbsolutePath($package);
        $configPath = "{$path}/{$this->configFile}";
        if (is_file($configPath)) {
            $config = $this->readConfig($configPath);
        }

        parent::install($repo, $package);

        if (!isset($config)) {
            $config = $this->readConfig($configPath);
        }
        $config['version'] = $package->getPrettyVersion();
        $this->writeConfig($configPath, $config);
    }
}
