<?php

namespace Boots\Installer;

/**
 * This file is part of the Boots\Installer package.
 *
 * @package    Boots\Installer
 * @subpackage FrameworkInstaller
 * @author     Kamal Khan <shout@bhittani.com>
 * @version    1.x
 * @see        http://wpboots.com
 * @link       https://github.com/wpboots/installer
 * @copyright  2014-2017 Kamal Khan
 * @license    https://github.com/wpboots/installer/blob/master/LICENSE
 */

use PhpParser\Error;
use PhpParser\NodeTraverser;
use PhpParser\ParserFactory;
use Composer\Package\PackageInterface;
use PhpParser\NodeVisitor\NameResolver;
use Composer\Installer\LibraryInstaller;
use Bhittani\PhpParser\AppendSuffixVisitor;
use PhpParser\PrettyPrinter\Standard as PhpPrinter;
use Composer\Repository\InstalledRepositoryInterface;

/**
 * @package Boots\Installer
 * @subpackage FrameworkInstaller
 */
class FrameworkInstaller extends LibraryInstaller
{
    /**
     * Extension type.
     * @var string
     */
    protected $framework = 'boots/boots';

    /**
     * Target directory (relative to project).
     * @var string
     */
    protected $targetDir = 'boots';

    /**
     * Config file (relative to package).
     * @var string
     */
    protected $configFile = 'boots.php';

    protected static function readConfig($path)
    {
        $config = [
            'version' => '',
            'mounted' => false,
            'extensions' => [],
            'autoload' => [],
        ];

        if (is_file($path)) {
            $config = require $path;
        }

        return $config;
    }

    protected static function writeConfig($path, array $config)
    {
        $contents = '<?php ' . PHP_EOL;
        $contents .= '// This file is automatically generated by the' . PHP_EOL;
        $contents .= '// boots framework and SHOULD NOT be modified directly.' . PHP_EOL;
        $contents .= 'return ' . var_export($config, true) . ';' . PHP_EOL;
        file_put_contents($path, $contents);
    }

    protected function getAbsolutePath(PackageInterface $package)
    {
        // return $this->composer->getInstallationManager()->getInstallPath($package);
        $baseDir = dirname($this->composer->getConfig()->getConfigSource()->getName());
        $installPath = $this->getInstallPath($package);
        return "{$baseDir}/{$installPath}";
    }

    protected function mount(PackageInterface $package)
    {
        $path = $this->getAbsolutePath($package);
        $version = $package->getPrettyVersion();
        $autoloads = $package->getAutoload();

        $suffix = str_replace('.', '_', $version);
        $suffix = str_replace('-', '_', $suffix);
        $suffix = empty($suffix) ? '' : "_{$suffix}";

        $regexes = [];
        foreach (array_keys($autoloads['psr-4']) as $prefix) {
            $regexes['/^\\\\?' . preg_quote($prefix) . '/'] = $suffix;
        }
        $traverser = new NodeTraverser;
        $traverser->addVisitor(new AppendSuffixVisitor($suffix, $regexes));

        $printer = new PhpPrinter;
        $parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);

        foreach (array_values($autoloads['psr-4']) as $rpath) {
            $dir = $path . '/' . trim($rpath, '/');
            if (!is_dir($dir)) {
                continue;
            }
            $files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir));
            $files = new \RegexIterator($files, '/\.php$/');
            foreach ($files as $file) {
                try {
                    // read the file that should be converted
                    $code = file_get_contents($file);
                    // parse
                    $stmts = $parser->parse($code);
                    // traverse
                    $stmts = $traverser->traverse($stmts);
                    // pretty print
                    $code = $printer->prettyPrintFile($stmts);
                    // write the converted file to the target directory
                    file_put_contents($file, $code . PHP_EOL);
                } catch (Error $e) {
                    echo 'Parse Error: ', $e->getMessage();
                }
            }
        }
    }

    /**
     * {@inheritDoc}
     */
    public function getInstallPath(PackageInterface $package)
    {
        if ($package->getPrettyName() !== $this->framework) {
            return parent::getInstallPath($package);
        }

        return $this->targetDir;
    }

    /**
     * {@inheritDoc}
     */
    public function supports($packageType)
    {
        return $packageType === 'framework';
    }

    /**
     * {@inheritDoc}
     */
    public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        if ($package->getPrettyName() !== $this->framework) {
            return parent::install($repo, $package);
        }

        $path = $this->getAbsolutePath($package);
        $configPath = "{$path}/{$this->configFile}";
        if (is_file($configPath)) {
            $config = $this->readConfig($configPath);
        }

        parent::install($repo, $package);

        $this->mount($package);

        if (!isset($config)) {
            $config = $this->readConfig($configPath);
        }
        $config['version'] = $package->getPrettyVersion();
        $config['autoload'] = $package->getAutoload();
        $this->writeConfig($configPath, $config);
    }
}
